import { createContext, useContext, useEffect, useMemo, useState } from "react";

const STORAGE_LANGUAGE = "agri_ui_language";
const STORAGE_THEME = "agri_ui_theme";

const translations = {
  Contact: "संपर्क",
  "Sign Up": "साइन अप",
  Signup: "साइन अप",
  Login: "लॉगिन",
  Prediction: "पूर्वानुमान",
  "Crop Prediction": "फसल पूर्वानुमान",
  "Yield Prediction": "उपज पूर्वानुमान",
  "Rainfall Prediction": "वर्षा पूर्वानुमान",
  Recommendation: "सिफारिश",
  "Crop Recommendation": "फसल सिफारिश",
  "Fertilizer Recommendation": "उर्वरक सिफारिश",
  Trade: "व्यापार",
  "Trade Crops": "फसल व्यापार",
  "Crop Stocks": "फसल स्टॉक",
  "Crop Stock": "फसल स्टॉक",
  "Selling History": "बिक्री इतिहास",
  Tools: "उपकरण",
  "Chat Bot": "चैट बॉट",
  "Weather Forecast": "मौसम पूर्वानुमान",
  "News Feed": "समाचार",
  Logout: "लॉगआउट",
  "Buy Crops": "फसल खरीदें",
  Invoices: "चालान",
  Farmers: "किसान",
  Customers: "ग्राहक",
  Queries: "प्रश्न",
  "Our Address": "हमारा पता",
  Call: "कॉल",
  Email: "ईमेल",
  Marketplace: "मार्केटप्लेस",
  Refresh: "रिफ्रेश",
  Insight: "जानकारी",
  Features: "विशेषताएं",
  Stack: "टेक स्टैक",
  "Technologies Used": "उपयोग की गई तकनीकें",
  "Agriculture News": "कृषि समाचार",
  "Forecast Preview": "मौसम पूर्वावलोकन",
  "Featured Market Crops": "मुख्य बाजार फसलें",
  "Contact Us": "संपर्क करें",
  "Send Message": "संदेश भेजें",
  Name: "नाम",
  Mobile: "मोबाइल",
  Address: "पता",
  Message: "संदेश",
  Visit: "देखें",
  "Payment Integration (Razorpay)": "पेमेंट इंटीग्रेशन (रेजरपे)",
  "Login / Register": "लॉगिन / रजिस्टर",
  "The next step in farming": "खेती का अगला कदम",
  "Highly reliable and accurate.": "बहुत विश्वसनीय और सटीक।",
  "Faster and responsive website.": "तेज और रिस्पॉन्सिव वेबसाइट।",
  "Real time weather forecast.": "रीयल टाइम मौसम पूर्वानुमान।",
  "Integrated news feature.": "एकीकृत समाचार सुविधा।",
  "News, Weather & Contact": "समाचार, मौसम और संपर्क",
  "Secure Access": "सुरक्षित प्रवेश",
  "Choose sign in method": "साइन-इन तरीका चुनें",
  "Role-based access": "भूमिका आधारित प्रवेश",
  "Verified entry": "सत्यापित प्रवेश",
  "Profile completion": "प्रोफ़ाइल पूर्णता",
  Role: "भूमिका",
  Farmer: "किसान",
  Customer: "ग्राहक",
  Admin: "एडमिन",
  Manual: "मैनुअल",
  Quick: "त्वरित",
  "After entry": "प्रवेश के बाद",
  "Email and password": "ईमेल और पासवर्ड",
  "Mobile OTP or Google": "मोबाइल ओटीपी या गूगल",
  "Complete missing profile details": "बाकी प्रोफ़ाइल विवरण पूरा करें",
  "Secure access for a smarter agricultural marketplace.":
    "एक बेहतर कृषि मार्केटप्लेस के लिए सुरक्षित प्रवेश।",
  "Sign in or create your account": "लॉगिन करें या अपना खाता बनाएं",
  "Select a crop and enter a valid quantity first": "पहले फसल चुनें और सही मात्रा दर्ज करें",
  "Item added to order details": "आइटम ऑर्डर विवरण में जोड़ दिया गया",
  "Add at least one item to order details first": "पहले ऑर्डर विवरण में कम से कम एक आइटम जोड़ें",
  "Unable to load crop listings": "फसल सूची लोड नहीं हो सकी",
  "Loading crop marketplace...": "फसल मार्केटप्लेस लोड हो रहा है...",
  "Search crop": "फसल खोजें",
  "Sort by stock": "स्टॉक के अनुसार क्रमबद्ध करें",
  "Sort by price": "कीमत के अनुसार क्रमबद्ध करें",
  "Sort by name": "नाम के अनुसार क्रमबद्ध करें",
  "No crop listings are available for purchase right now.":
    "अभी खरीद के लिए कोई फसल सूची उपलब्ध नहीं है।",
  "Crop Name": "फसल का नाम",
  "Quantity (in KG)": "मात्रा (किलो में)",
  "Price (in Rs)": "कीमत (रु में)",
  "Add Item": "आइटम जोड़ें",
  "Select Crop": "फसल चुनें",
  "Enter kg": "किलो दर्ज करें",
  "Add To Cart": "कार्ट में जोड़ें",
  "Order Details": "ऑर्डर विवरण",
  "Item Name": "आइटम का नाम",
  "Quantity (KG)": "मात्रा (किलो)",
  "Rate (Rs.)": "रेट (रु.)",
  "Total (Rs.)": "कुल (रु.)",
  Action: "कार्रवाई",
  Remove: "हटाएं",
  "Cart Total": "कार्ट कुल",
  "Buy All Now": "सब अभी खरीदें",
  "Pay Cart with Razorpay": "रेजरपे से कार्ट भुगतान करें",
  "No item added yet": "अभी कोई आइटम नहीं जोड़ा गया",
  "Payment Options": "भुगतान विकल्प",
  "Add items to the cart first, then use Pay Cart with Razorpay for a single checkout.":
    "पहले आइटम कार्ट में जोड़ें, फिर एक ही भुगतान के लिए रेजरपे से भुगतान करें।",
  "Enter a quantity between 1 and stock kg.": "1 से उपलब्ध स्टॉक तक मात्रा दर्ज करें।",
  "Loading weather forecast...": "मौसम पूर्वानुमान लोड हो रहा है...",
  "Search city or location like Delhi, Mumbai, Udupi":
    "दिल्ली, मुंबई, उडुपी जैसी जगह खोजें",
  "Search Weather": "मौसम खोजें",
  "Searching...": "खोजा जा रहा है...",
  Date: "तारीख",
  Time: "समय",
  "Temperature (Max / Min)": "तापमान (अधिकतम / न्यूनतम)",
  Description: "विवरण",
  Humidity: "नमी",
  Wind: "हवा",
  "No forecast data is available right now.": "अभी कोई मौसम डेटा उपलब्ध नहीं है।",
  "Enter a city or real location name first": "पहले शहर या सही स्थान का नाम दर्ज करें",
  "Unable to load weather forecast": "मौसम पूर्वानुमान लोड नहीं हो सका",
  "Ask anything about crops, soil, fertilizer, weather, or farm planning.":
    "फसल, मिट्टी, उर्वरक, मौसम या खेती की योजना के बारे में कुछ भी पूछें।",
  You: "आप",
  Send: "भेजें",
  "Sending...": "भेजा जा रहा है...",
  "Ask something about agriculture...": "कृषि के बारे में कुछ पूछें...",
  "Chatbot is unavailable right now": "चैटबॉट अभी उपलब्ध नहीं है",
  "I could not answer right now. Please try again in a moment.":
    "मैं अभी जवाब नहीं दे सका। कृपया थोड़ी देर बाद फिर प्रयास करें।",
  "No response received from the assistant.": "सहायक से कोई जवाब प्राप्त नहीं हुआ।",
  "Direct Contact": "सीधा संपर्क",
  Profiles: "प्रोफाइल",
  "Full Name": "पूरा नाम",
  "Mobile Number": "मोबाइल नंबर",
  "Email Id": "ईमेल आईडी",
  "Farmer Dashboard": "किसान डैशबोर्ड",
  "Customer Dashboard": "ग्राहक डैशबोर्ड",
  "Orders fulfilled": "पूरे किए गए ऑर्डर",
  "Revenue tracked": "ट्रैक की गई आय",
  "Current listings": "वर्तमान लिस्टिंग",
  "Total listed quantity": "कुल सूचीबद्ध मात्रा",
  "List crop for sale": "बिक्री के लिए फसल सूचीबद्ध करें",
  Quantity: "मात्रा",
  "Cost per kg": "प्रति किलो लागत",
  "Add Listing": "लिस्टिंग जोड़ें",
  Listings: "लिस्टिंग",
  "Current crop listings": "वर्तमान फसल लिस्टिंग",
  Weather: "मौसम",
  Forecast: "पूर्वानुमान",
  News: "समाचार",
  "Farmer news feed": "किसान समाचार फीड",
  Performance: "प्रदर्शन",
  "Sales insights": "बिक्री जानकारी",
  Pricing: "मूल्य निर्धारण",
  "Listing health": "लिस्टिंग स्थिति",
  Predictions: "पूर्वानुमान",
  "Agriculture ML tools": "कृषि एमएल टूल्स",
  "Select state": "राज्य चुनें",
  "Select district": "जिला चुनें",
  Season: "मौसम",
  "Predict crop": "फसल पूर्वानुमान करें",
  "Waiting for input": "इनपुट की प्रतीक्षा है",
  Nitrogen: "नाइट्रोजन",
  Phosphorous: "फॉस्फोरस",
  Potassium: "पोटैशियम",
  Temperature: "तापमान",
  "pH": "पीएच",
  Rainfall: "वर्षा",
  "Recommend crop": "फसल सुझाएं",
  "Soil moisture": "मिट्टी की नमी",
  "Soil type": "मिट्टी का प्रकार",
  "Crop type": "फसल का प्रकार",
  "Recommend fertilizer": "उर्वरक सुझाएं",
  Subdivision: "उपखंड",
  "Select month": "महीना चुनें",
  "Predict rainfall": "वर्षा पूर्वानुमान करें",
  "State name": "राज्य का नाम",
  "District name": "जिले का नाम",
  Crop: "फसल",
  Area: "क्षेत्रफल",
  "Predict yield": "उपज पूर्वानुमान करें",
  "Loading farmer dashboard...": "किसान डैशबोर्ड लोड हो रहा है...",
  "Unable to load farmer dashboard": "किसान डैशबोर्ड लोड नहीं हो सका",
  "Loading customer dashboard...": "ग्राहक डैशबोर्ड लोड हो रहा है...",
  "Unable to load customer dashboard": "ग्राहक डैशबोर्ड लोड नहीं हो सका",
  Invoice: "चालान",
  "Invoice Details": "चालान विवरण",
  "Download / Print": "डाउनलोड / प्रिंट",
  "Back to Invoices": "चालानों पर वापस जाएं",
  Payment: "भुगतान",
  Reference: "रेफरेंस",
  "Billing Details": "बिलिंग विवरण",
  Subtotal: "उप-योग",
  Total: "कुल",
  "Invoice History": "चालान इतिहास",
  "Invoice No.": "चालान नंबर",
  "Payment Method": "भुगतान तरीका",
  "View Invoice": "चालान देखें",
  "No invoices yet": "अभी कोई चालान नहीं है",
  Profile: "प्रोफ़ाइल",
  Welcome: "स्वागत है",
  Cancel: "रद्द करें",
  "Edit Profile": "प्रोफ़ाइल संपादित करें",
  "Customer ID": "ग्राहक आईडी",
  "Customer Name": "ग्राहक नाम",
  "Email Address": "ईमेल पता",
  "Mobile No": "मोबाइल नंबर",
  City: "शहर",
  Pincode: "पिनकोड",
  Password: "पासवर्ड",
  "Your account was created with a quick method. Please complete the missing profile details below.":
    "आपका खाता त्वरित तरीके से बनाया गया था। कृपया नीचे बाकी प्रोफ़ाइल विवरण पूरा करें।",
  "New Password": "नया पासवर्ड",
  "Leave blank to keep current password": "वर्तमान पासवर्ड रखने के लिए खाली छोड़ें",
  "Save Profile": "प्रोफ़ाइल सेव करें",
  "Complete your profile details to unlock the rest of the customer portal.":
    "ग्राहक पोर्टल के बाकी हिस्से खोलने के लिए अपनी प्रोफ़ाइल पूरी करें।",
  "Farmer ID": "किसान आईडी",
  "Farmer Name": "किसान नाम",
  Gender: "लिंग",
  DOB: "जन्म तिथि",
  District: "जिला",
  "City / Location": "शहर / स्थान",
  "Complete your profile details to unlock the rest of the farmer portal.":
    "किसान पोर्टल के बाकी हिस्से खोलने के लिए अपनी प्रोफ़ाइल पूरी करें।",
  "Unable to load admin dashboard": "एडमिन डैशबोर्ड लोड नहीं हो सका",
  "Loading admin dashboard...": "एडमिन डैशबोर्ड लोड हो रहा है...",
  "Admin Dashboard": "एडमिन डैशबोर्ड",
  "Customers List": "ग्राहक सूची",
  Delete: "हटाएं",
  "Delete this customer from the SQL database?": "क्या इस ग्राहक को SQL डेटाबेस से हटाना है?",
  "Delete this farmer from the SQL database?": "क्या इस किसान को SQL डेटाबेस से हटाना है?",
  "Farmers List": "किसान सूची",
  "Date of Birth": "जन्म तिथि",
  "Contact Queries": "संपर्क प्रश्न",
  "Loading contact queries...": "संपर्क प्रश्न लोड हो रहे हैं...",
  "Unable to load contact queries": "संपर्क प्रश्न लोड नहीं हो सके",
  "Delete this contact query?": "क्या यह संपर्क प्रश्न हटाना है?",
  "No contact queries found.": "कोई संपर्क प्रश्न नहीं मिला।",
  "Produced Crops": "उत्पादित फसलें",
  "Crop Availability": "फसल उपलब्धता",
  "Update Crop Stock": "फसल स्टॉक अपडेट करें",
  "Current Market Avg Price for": "वर्तमान बाजार औसत कीमत",
  "Unable to load current market average price.": "वर्तमान बाजार औसत कीमत लोड नहीं हो सकी।",
  "Crop details added successfully. Current market average for":
    "फसल विवरण सफलतापूर्वक जोड़ा गया। वर्तमान बाजार औसत",
  "and MSP is Rs.": "और MSP है रु.",
  "Unable to add crop details.": "फसल विवरण नहीं जोड़ा जा सका।",
  "Cost borne by farmer per KG (in Rs)": "किसान द्वारा प्रति किलो लागत (रु में)",
  "Upload CROP Details": "फसल विवरण अपलोड करें",
  Submit: "सबमिट करें",
  "Submitting...": "सबमिट हो रहा है...",
  Result: "परिणाम",
  "Prediction failed": "पूर्वानुमान विफल हुआ",
  Predict: "पूर्वानुमान करें",
  "Select Season ...": "मौसम चुनें ...",
  "Predicting...": "पूर्वानुमान चल रहा है...",
  "Recommendation failed": "सिफारिश विफल हुई",
  Recommend: "सुझाएं",
  "Recommending...": "सिफारिश की जा रही है...",
  "Select Soil Type": "मिट्टी का प्रकार चुनें",
  "Select Region": "क्षेत्र चुनें",
  "Select Month": "महीना चुनें",
  "Select a district": "जिला चुनें",
  "Select crop": "फसल चुनें",
  "Area in Hectares": "क्षेत्रफल हेक्टेयर में",
  "News List": "समाचार सूची",
  Image: "छवि",
  Title: "शीर्षक",
  Author: "लेखक",
  Published: "प्रकाशित",
  "Total Amount received (in Rs)": "प्राप्त कुल राशि (रु में)",
  "Date of Transaction": "लेनदेन की तारीख",
  "No crops currently available.": "अभी कोई फसल उपलब्ध नहीं है।",
  "Loading crop availability...": "फसल उपलब्धता लोड हो रही है...",
  "Unable to load crop availability": "फसल उपलब्धता लोड नहीं हो सकी",
  Buy: "खरीदें",
  State: "राज्य",
  is: "है",
  "Select season": "मौसम चुनें",
  "Admin has access to all the data in": "एडमिन को सभी डेटा तक पहुंच है",
  "Admin can modify and view all the customer details when necessary.":
    "एडमिन आवश्यकता होने पर सभी ग्राहक विवरण देख और संशोधित कर सकता है।",
  "Admin can manage the farmer details who provide supplies to the store.":
    "एडमिन उन किसानों के विवरण प्रबंधित कर सकता है जो आपूर्ति प्रदान करते हैं।",
  "Admin also has access to the sales report and can sort them as required.":
    "एडमिन को बिक्री रिपोर्ट तक भी पहुंच है और वह उन्हें आवश्यकता अनुसार व्यवस्थित कर सकता है।",
};

const UiContext = createContext(null);

export function UiProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem(STORAGE_LANGUAGE) || "en");
  const [theme, setTheme] = useState(() => localStorage.getItem(STORAGE_THEME) || "light");

  useEffect(() => {
    localStorage.setItem(STORAGE_LANGUAGE, language);
    document.documentElement.setAttribute("lang", language === "hi" ? "hi" : "en");
  }, [language]);

  useEffect(() => {
    localStorage.setItem(STORAGE_THEME, theme);
    document.documentElement.dataset.theme = theme;
    document.body.dataset.theme = theme;
  }, [theme]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      toggleLanguage: () => setLanguage((current) => (current === "en" ? "hi" : "en")),
      theme,
      setTheme,
      toggleTheme: () => setTheme((current) => (current === "light" ? "dark" : "light")),
      t: (text) => (language === "hi" ? translations[text] || text : text),
    }),
    [language, theme],
  );

  return <UiContext.Provider value={value}>{children}</UiContext.Provider>;
}

export function useUi() {
  return useContext(UiContext);
}
